# Generated by Django 5.2.17 on 2026-09-11 04:00

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(help_text='Business registration number.', max_length=64, unique=True)),
                ('contact_phone', apps.core.fields.PhoneNumberField(max_length=16)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['status'], name='operators_operator_status_idx'), models.Index(fields=['company_name'], name='operators_operator_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'suspended'])), name='operators_operator_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='OperatorMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='operators.operator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['operator', 'created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='operators_membership_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('operator', 'user'), name='operators_membership_unique'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'manager', 'staff'])), name='operators_membership_role_valid')],
            },
        ),
    ]
