# Generated by Django 5.2.17 on 2026-09-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_engine_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='boarded_at',
            field=models.DateTimeField(blank=True, help_text='When the crew checked this passenger onto the bus.', null=True),
        ),
    ]
