# Generated by Django 5.2.17 on 2026-09-12 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_passenger_boarded_at'),
        ('routes', '0002_route_base_fare_and_case_insensitive_stops'),
        ('trips', '0004_trip_integrity_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='bookings_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'cancelled_at'], name='bookings_cancelled_at_idx'),
        ),
    ]
