# Generated by Django 5.2.17 on 2026-09-13 07:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_report_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ticket', 'E-ticket'), ('ticket_resent', 'E-ticket sent again'), ('trip_reminder', 'Departure reminder'), ('sign_in_code', 'Sign-in code')], max_length=24)),
                ('channel', models.CharField(choices=[('sms', 'Text message'), ('email', 'E-mail')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Waiting to send'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Not sent')], default='pending', max_length=12)),
                ('recipient', models.CharField(help_text='An E.164 phone number or an e-mail.', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Exactly what was sent (sign-in codes are never stored).')),
                ('html', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, help_text='A sender has claimed this message until then.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notifications_due_idx'), models.Index(fields=['booking', '-created_at'], name='notifications_booking_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='notifications_dedupe_key_unique'), models.CheckConstraint(condition=models.Q(('kind__in', ['ticket', 'ticket_resent', 'trip_reminder', 'sign_in_code'])), name='notifications_kind_valid'), models.CheckConstraint(condition=models.Q(('channel__in', ['sms', 'email'])), name='notifications_channel_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'sending', 'sent', 'failed', 'skipped'])), name='notifications_status_valid')],
            },
        ),
    ]
