# Generated by Django 5.2.17 on 2026-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_trip_activity_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('cancelled', 'Cancelled'), ('status_changed', 'Status changed'), ('generated', 'Generated trips'), ('refunded', 'Refunded')], max_length=16),
        ),
    ]
