# Generated by Django 5.2.17 on 2026-09-11 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(help_text='Vehicle registration, e.g. NB-1234.', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Display label, e.g. 'Kandy Express'.", max_length=100)),
                ('bus_type', models.CharField(choices=[('normal', 'Normal'), ('semi_luxury', 'Semi luxury'), ('luxury', 'Luxury (A/C)'), ('super_luxury', 'Super luxury')], default='normal', max_length=16)),
                ('seat_capacity', models.PositiveSmallIntegerField()),
                ('layout_type', models.CharField(choices=[('2x2', '2 + 2'), ('2x3', '2 + 3'), ('1x2', '1 + 2')], default='2x2', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='operators.operator')),
            ],
            options={
                'verbose_name_plural': 'buses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['operator', 'active'], name='fleet_bus_operator_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('seat_capacity__gte', 1), ('seat_capacity__lte', 90)), name='fleet_bus_seat_capacity_range'), models.CheckConstraint(condition=models.Q(('bus_type__in', ['normal', 'semi_luxury', 'luxury', 'super_luxury'])), name='fleet_bus_type_valid'), models.CheckConstraint(condition=models.Q(('layout_type__in', ['2x2', '2x3', '1x2'])), name='fleet_bus_layout_valid')],
            },
        ),
    ]
