# Generated by Django 5.2.17 on 2026-09-11 05:00

import apps.fleet.validators
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


def retire_semi_luxury(apps, schema_editor):
    """Phase 1 bus classes are Normal / AC / Luxury / Super Luxury; semi-luxury becomes Normal."""
    Bus = apps.get_model("fleet", "Bus")
    Bus.objects.filter(bus_type="semi_luxury").update(bus_type="normal")


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_number', models.CharField(max_length=8)),
                ('row', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
                ('seat_type', models.CharField(choices=[('normal', 'Normal'), ('window', 'Window'), ('aisle', 'Aisle'), ('driver', 'Driver'), ('conductor', 'Conductor'), ('reserved', 'Reserved')], default='normal', max_length=12)),
                ('is_available', models.BooleanField(default=True, help_text='Unavailable seats (broken, blocked off) are never sold.')),
            ],
            options={
                'ordering': ['row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('layout_type', models.CharField(choices=[('2x2', '2 + 2'), ('2x1', '2 + 1'), ('custom', 'Custom')], default='2x2', max_length=8)),
                ('rows', models.PositiveSmallIntegerField()),
                ('columns', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bus',
            name='fleet_bus_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='bus',
            name='fleet_bus_layout_valid',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='layout_type',
        ),
        migrations.AddField(
            model_name='bus',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ac', 'AC'), ('wifi', 'WiFi'), ('usb_charging', 'USB charging'), ('reclining_seats', 'Reclining seats'), ('tv', 'TV'), ('toilet', 'Toilet')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('ac', 'AC'), ('luxury', 'Luxury'), ('super_luxury', 'Super Luxury')], default='normal', max_length=16),
        ),
        # Must run before the new fleet_bus_type_valid constraint is added below.
        migrations.RunPython(retire_semi_luxury, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(help_text='Vehicle registration, e.g. NB-1234 or WP NB-1234.', max_length=20, unique=True, validators=[apps.fleet.validators.validate_registration_number]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_capacity',
            field=models.PositiveSmallIntegerField(help_text='Seats sold per trip.'),
        ),
        migrations.AddConstraint(
            model_name='seatlayout',
            constraint=models.CheckConstraint(condition=models.Q(('rows__gte', 1), ('rows__lte', 25)), name='fleet_layout_rows_range'),
        ),
        migrations.AddConstraint(
            model_name='seatlayout',
            constraint=models.CheckConstraint(condition=models.Q(('columns__gte', 2), ('columns__lte', 7)), name='fleet_layout_columns_range'),
        ),
        migrations.AddConstraint(
            model_name='seatlayout',
            constraint=models.CheckConstraint(condition=models.Q(('layout_type__in', ['2x2', '2x1', 'custom'])), name='fleet_layout_type_valid'),
        ),
        migrations.AddField(
            model_name='seat',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fleet.seatlayout'),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='fleet.seatlayout'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=django.contrib.postgres.indexes.GinIndex(fields=['facilities'], name='fleet_bus_facilities_gin'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.CheckConstraint(condition=models.Q(('bus_type__in', ['normal', 'ac', 'luxury', 'super_luxury'])), name='fleet_bus_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.CheckConstraint(condition=models.Q(('facilities__contained_by', ['ac', 'wifi', 'usb_charging', 'reclining_seats', 'tv', 'toilet'])), name='fleet_bus_facilities_valid'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('layout', 'seat_number'), name='fleet_seat_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('layout', 'row', 'column'), name='fleet_seat_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(condition=models.Q(('column__gte', 1), ('row__gte', 1)), name='fleet_seat_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(condition=models.Q(('seat_type__in', ['normal', 'window', 'aisle', 'driver', 'conductor', 'reserved'])), name='fleet_seat_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('seat_type__in', ('driver', 'conductor')), _negated=True), ('is_available', False), _connector='OR'), name='fleet_seat_crew_not_bookable'),
        ),
    ]
