# Generated by Django 5.2.17 on 2026-09-11 04:00

import datetime
import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('route_number', models.CharField(blank=True, help_text='Official route number, e.g. 01 or 87.', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city'], name='routes_stop_city_idx'), models.Index(fields=['name'], name='routes_stop_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='routes_stop_name_city_unique'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='routes_stop_coordinates_valid')],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='1-based position along the route.')),
                ('arrival_offset', models.DurationField(default=datetime.timedelta(0))),
                ('departure_offset', models.DurationField(default=datetime.timedelta(0))),
                ('is_boarding_point', models.BooleanField(default=True)),
                ('is_dropoff_point', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='routes.stop')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_ending_here', to='routes.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_starting_here', to='routes.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', through='routes.RouteStop', to='routes.stop'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('route', 'sequence'), name='routes_routestop_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop'), name='routes_routestop_stop_unique'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='routes_routestop_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.CheckConstraint(condition=models.Q(('arrival_offset__gte', datetime.timedelta(0))), name='routes_routestop_arrival_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.CheckConstraint(condition=models.Q(('departure_offset__gte', models.F('arrival_offset'))), name='routes_routestop_departs_after_arrival'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination', 'active'], name='routes_route_endpoints_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_number'], name='routes_route_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='routes_route_distinct_endpoints'),
        ),
    ]
