# Generated by Django 5.2.17 on 2026-09-11 05:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stop',
            name='routes_stop_name_city_unique',
        ),
        migrations.AddField(
            model_name='route',
            name='base_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard full-journey fare in LKR; individual trips may override it.', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('base_fare__isnull', True), ('base_fare__gte', 0), _connector='OR'), name='routes_route_fare_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('city'), name='routes_stop_name_city_ci_unique'),
        ),
    ]
