# Generated by Django 5.2.17 on 2026-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_base_fare_and_case_insensitive_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='path',
            field=models.TextField(blank=True, help_text='The road route as an encoded polyline (precision 5), origin to destination.'),
        ),
        migrations.AddField(
            model_name='route',
            name='path_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='path_duration_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='path_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='route',
            name='path_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
