# Generated by Django 5.2.17 on 2026-09-11 04:00

import apps.payments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_reference', models.CharField(default=apps.payments.models.generate_transaction_reference, editable=False, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=16)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('mobile_wallet', 'Mobile wallet'), ('cash', 'Cash')], max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='payments_booking_status_idx'), models.Index(fields=['status', 'created_at'], name='payments_status_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('transaction_reference',), name='payments_transaction_reference_unique'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['initiated', 'pending', 'succeeded', 'failed', 'refunded'])), name='payments_status_valid'), models.CheckConstraint(condition=models.Q(('payment_method__in', ['card', 'bank_transfer', 'mobile_wallet', 'cash'])), name='payments_method_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payments_succeeded_has_paid_at')],
            },
        ),
    ]
