# Generated by Django 5.2.17 on 2026-09-11 21:47
# Split by hand: schema here, status backfill in 0003, new constraints in 0004.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_engine_constraints'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=160)),
                ('source', models.CharField(choices=[('webhook', 'Gateway notification'), ('reconcile', 'Status check'), ('checkout', 'Checkout started'), ('customer', 'Customer'), ('admin', 'Administrator'), ('system', 'System')], max_length=16)),
                ('status', models.CharField(blank=True, help_text='Status the event reported.', max_length=20)),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('ignored', 'Ignored (already handled)'), ('rejected', 'Rejected')], max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['payment', 'created_at'], name='payments_event_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='payments_event_unique')],
            },
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_method_valid',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_succeeded_has_paid_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="When the booking's seat hold for this attempt ends.", null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        # Payments before this phase were all recorded by staff.
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='manual', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='requires_refund',
            field=models.BooleanField(default=False, help_text="Money was taken but the booking couldn't stand (seats gone, trip cancelled, paid twice…). Refund it."),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank_transfer', 'Online banking'), ('mobile_wallet', 'Mobile wallet'), ('cash', 'Cash')], max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='pending', max_length=20),
        ),
    ]
