# Generated by Django 5.2.17 on 2026-09-11 23:13

import apps.payments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_engine_constraints'),
        ('payments', '0004_payment_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.payments.models.generate_refund_reference, editable=False, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='requested', max_length=16)),
                ('reason', models.CharField(blank=True, help_text='Why the refund was asked for.', max_length=255)),
                ('resolution', models.CharField(blank=True, help_text='What the team decided.', max_length=255)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='bookings.booking')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_refund_status_idx'), models.Index(fields=['booking', '-created_at'], name='payments_refund_booking_idx')],
                'constraints': [models.UniqueConstraint(fields=('reference',), name='payments_refund_reference_unique'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_refund_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['requested', 'processing', 'completed', 'rejected'])), name='payments_refund_status_valid'), models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'processing'))), fields=('payment',), name='payments_one_open_refund_per_payment'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('completed', 'rejected')), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='payments_refund_resolved_has_time')],
            },
        ),
    ]
