# Generated by Django 5.2.17 on 2026-09-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_report_indexes'),
        ('payments', '0005_refund_requests'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payments_status_paid_idx'),
        ),
    ]
