# Generated by Django 5.2.17 on 2026-09-11 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_engine_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(editable=False, max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='bookings.booking')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('ticket_number',), name='tickets_ticket_number_unique')],
            },
        ),
    ]
