# Generated by Django 5.2.17 on 2026-09-11 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Fare per seat (LKR).', max_digits=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route')),
            ],
            options={
                'ordering': ['departure_datetime'],
                'indexes': [models.Index(fields=['route', 'departure_datetime'], name='trips_trip_route_departure_idx'), models.Index(fields=['status', 'departure_datetime'], name='trips_trip_status_depart_idx')],
                'constraints': [models.UniqueConstraint(fields=('bus', 'departure_datetime'), name='trips_trip_bus_departure_unique'), models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='trips_trip_price_non_negative'), models.CheckConstraint(condition=models.Q(('status__in', ['scheduled', 'boarding', 'departed', 'completed', 'cancelled'])), name='trips_trip_status_valid')],
            },
        ),
    ]
